name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Android workload
        shell: pwsh
        run: dotnet workload install android

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Restore
        shell: pwsh
        run: dotnet restore

      - name: Build Debug APK
        shell: pwsh
        run: dotnet build -f net8.0-android -c Debug /p:AndroidPackageFormat=apk

      - name: Locate APK
        id: find_apk
        shell: pwsh
        run: |
          $apk = Get-ChildItem -Recurse -File "bin\Debug\net8.0-android\**\*.apk" |
                 Sort-Object LastWriteTime | Select-Object -Last 1
          if (-not $apk) { throw "No APK generated" }
          "path=$($apk.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: didioverlay-debug-apk
          path: ${{ steps.find_apk.outputs.path }}
